#!/usr/bin/env bash
# Regenerates the window/desktop icon from the ruled suite mark.
#
#   assets/oracle.svg        — verbatim copy of empyrean `design/icons/oracle.svg` (origin/main 51dd032);
#                              stroke-only, `currentColor`, 96×96 viewBox. Re-copy it when empyrean re-rules it.
#   assets/oracle-icon.svg   — GENERATED: the mark tinted with the Oracle accent (`color.accent.oracle`
#                              = #38BDF8, tokens.json) at the stroke widths the suite chrome draws it with
#                              (design/previews/chrome-oracle.html, titlebar `.mark`), over a `surface`
#                              (#12151E) disc so it reads on any panel colour.
#   assets/oracle-{32,64,128,256}.png — GENERATED rasters for the .desktop / hicolor install.
#   assets/oracle-icon.argb  — GENERATED: what the binary embeds for X11 `_NET_WM_ICON`. Records of
#                              [u32 BE width][u32 BE height][width*height × u32 BE ARGB], sizes 32, 64, 128
#                              concatenated (one _NET_WM_ICON property may carry several sizes).
#
# Needs: rsvg-convert (librsvg), python3 + Pillow. Run from anywhere; writes next to itself.
set -euo pipefail
cd "$(dirname "$0")"

python3 - <<'PY'
import re
src = open("oracle.svg").read()
# Chrome stroke widths (chrome-oracle.html .mark) for the icon file's own widths.
widths = {"1.4": "2.4", "1": "1.4", "1.8": "3"}
body = re.sub(r'stroke-width="([0-9.]+)"', lambda m: f'stroke-width="{widths[m.group(1)]}"', src)
body = body.replace("currentColor", "#38BDF8")
# Strip the outer <svg> so the mark can be nested under a ground disc.
inner = re.search(r"<svg[^>]*>(.*)</svg>", body, re.S).group(1)
inner = inner.replace("<title>Oracle</title>", "")
out = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96" role="img" aria-label="Oracle">
  <!-- GENERATED by gen-icon.sh from oracle.svg — do not hand-edit. -->
  <title>Oracle</title>
  <defs>
    <filter id="glow" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="1.1" result="b"/>
      <feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
  </defs>
  <circle cx="48" cy="48" r="48" fill="#12151E"/>
  <g filter="url(#glow)" fill="none" stroke="#38BDF8" stroke-linecap="round" stroke-linejoin="round">{inner}</g>
</svg>
'''
open("oracle-icon.svg", "w").write(out)
PY

for s in 32 64 128 256; do
  rsvg-convert -w "$s" -h "$s" oracle-icon.svg -o "oracle-$s.png"
done

python3 - <<'PY'
import struct
from PIL import Image
with open("oracle-icon.argb", "wb") as f:
    for s in (32, 64, 128):
        im = Image.open(f"oracle-{s}.png").convert("RGBA")
        w, h = im.size
        f.write(struct.pack(">II", w, h))
        rgba = im.tobytes()
        for i in range(0, len(rgba), 4):
            r, g, b, a = rgba[i : i + 4]
            f.write(struct.pack(">I", (a << 24) | (r << 16) | (g << 8) | b))
print("wrote oracle-icon.argb")
PY
