//! **The player's `.desktop` entry must produce an argv THIS binary's parser accepts, and the check asks
//! the parser.**
//!
//! # The defect
//!
//! `oracle-player.desktop` was generated by `install-desktop.sh` through one line shared with the
//! frontend's entry: `sed "s|^Exec=.*|Exec=$exe %f|"`. That is a single command shape for two binaries
//! whose CLIs disagree. `oracle-frontend` takes its ROM positionally. This one requires `--rom PATH`, and
//! [the argument loop's fallthrough arm rejects positionals](../src/main.rs). Measured on the release
//! binary before the fix, with no change to it:
//!
//! ```text
//! oracle-player                        -> "--rom is required" + usage, no window
//! oracle-player /tmp/nope.bin          -> "unknown flag /tmp/nope.bin" + usage, no window
//! oracle-player --rom /nonexistent.bin -> "cannot read ROM ... (os error 2)"
//! ```
//!
//! The third line is the control: the parse SUCCEEDED there, so the first two are the parser refusing
//! rather than the file being absent. The desktop icon had therefore never been able to open a window,
//! with a file selected or without one, and it failed to a stderr that nobody clicking an icon reads.
//!
//! # Why this test lives here and not beside the installer's other tests
//!
//! The parser it has to agree with is in this crate. A test in `oracle-frontend` could only compare the
//! generated `Exec=` line against a string restating what this CLI accepts, and a restatement is a second
//! copy of the thing that went stale. Here, `CARGO_BIN_EXE_oracle-player` is built by the same `cargo
//! test` invocation that runs this file, so the binary is always present and always current: the check
//! can never silently become unmeasurable and pass anyway.
//!
//! # Why no window opens
//!
//! Two guards, both load-bearing:
//!
//! 1. The launcher is asked for its argv with `--print-argv`, which resolves the ROM and prints the
//!    command line and does not exec anything.
//! 2. The fixture ROM is DELETED between resolving that argv and running it, so the binary reaches
//!    `std::fs::read` and exits there. That is before any `eframe` context, any window and any Aether
//!    bind, which was confirmed by running `--rom /nonexistent.bin --aether` and seeing only the read
//!    error. The argv itself is never edited, so what runs is what the entry produces.
//!
//! `zenity` and `notify-send` are stubbed on `PATH` besides, because the launcher shows a dialog when it
//! refuses and a suite is not entitled to put a window on the machine running it.

#![cfg(unix)]

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;

fn launcher() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../oracle-frontend/assets/oracle-launch.sh")
}

fn installer() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../oracle-frontend/assets/install-desktop.sh")
}

/// A temporary tree with a stubbed `PATH`, removed on drop.
struct Rig {
    root: PathBuf,
}

impl Rig {
    fn new(name: &str) -> Self {
        let root = std::env::temp_dir().join(format!(
            "oracle-player-exec-{}-{}-{name}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("a clock after 1970")
                .as_nanos()
        ));
        fs::create_dir_all(root.join("share/applications")).expect("temp tree");
        let stubs = root.join("bin");
        fs::create_dir_all(&stubs).expect("stub dir");
        for tool in [
            "update-desktop-database",
            "gtk-update-icon-cache",
            "kbuildsycoca6",
            "zenity",
            "notify-send",
        ] {
            let p = stubs.join(tool);
            fs::write(&p, "#!/bin/sh\nexit 0\n").expect("stub");
            fs::set_permissions(&p, fs::Permissions::from_mode(0o755)).expect("stub mode");
        }
        Self { root }
    }

    fn path(&self) -> String {
        format!(
            "{}:{}",
            self.root.join("bin").display(),
            std::env::var("PATH").unwrap_or_default()
        )
    }

    /// Install into the temporary tree and hand back the player entry's `Exec=` line, so every assertion
    /// below is about the line a real install writes rather than one this file composed.
    fn installed_player_exec(&self, player_bin: &str) -> String {
        let out = Command::new("bash")
            .arg(installer())
            .arg("/bin/sh")
            .arg(player_bin)
            .env("HOME", &self.root)
            .env("XDG_DATA_HOME", self.root.join("share"))
            .env("XDG_CACHE_HOME", self.root.join("cache"))
            .env("XDG_CONFIG_HOME", self.root.join("config"))
            .env("PATH", self.path())
            .output()
            .expect("install-desktop.sh is runnable");
        let text = format!(
            "{}{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        );
        assert!(out.status.success(), "install-desktop.sh failed:\n{text}");
        let body = fs::read_to_string(self.root.join("share/applications/oracle-player.desktop"))
            .unwrap_or_else(|e| panic!("the player entry was not installed ({e}):\n{text}"));
        body.lines()
            .find(|l| l.starts_with("Exec="))
            .unwrap_or_else(|| panic!("no Exec= line in the installed entry:\n{body}"))
            .to_string()
    }
}

impl Drop for Rig {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

/// `%f` expanded the way a desktop expands it: to the picked file, or to nothing on a plain click.
fn exec_argv(exec: &str, rom: Option<&str>) -> Vec<String> {
    exec.trim_start_matches("Exec=")
        .split_whitespace()
        .filter_map(|tok| match (tok, rom) {
            ("%f", Some(r)) => Some(r.to_string()),
            ("%f", None) => None,
            _ => Some(tok.to_string()),
        })
        .collect()
}

/// Ask the launcher what it would exec, without letting it exec anything.
fn resolved_argv(mut argv: Vec<String>, path: &str, rom_env: Option<&str>) -> Vec<String> {
    argv.push("--print-argv".to_string());
    let mut cmd = Command::new(&argv[0]);
    cmd.args(&argv[1..]).env("PATH", path);
    if let Some(r) = rom_env {
        cmd.env("ORACLE_ROM", r);
    }
    let out = cmd.output().expect("the launcher is runnable");
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(out.status.success(), "the launcher resolved no launch:\n{text}");
    String::from_utf8_lossy(&out.stdout)
        .lines()
        .map(str::to_string)
        .collect()
}

/// Run an argv and collect everything it said. Callers must have made the ROM unreadable first.
fn say(argv: &[String]) -> String {
    let out = Command::new(&argv[0])
        .args(&argv[1..])
        .output()
        .expect("the player binary is runnable");
    format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    )
}

/// The gate. The installed entry, expanded as a desktop expands it, produces an argv this binary parses.
#[test]
fn the_installed_player_exec_is_an_argv_this_parser_accepts() {
    let rig = Rig::new("accepts");
    let bin = env!("CARGO_BIN_EXE_oracle-player");
    let exec = rig.installed_player_exec(bin);

    let rom = rig.root.join("fixture.bin");
    fs::write(&rom, b"not a real ROM").expect("fixture ROM");
    let argv = exec_argv(&exec, Some(&rom.display().to_string()));
    let launch = resolved_argv(argv, &rig.path(), None);

    assert_eq!(
        launch.first().map(String::as_str),
        Some(bin),
        "the launcher would run something other than the binary the entry names:\n{launch:?}"
    );
    assert!(
        launch.iter().any(|a| a == "--aether"),
        "--aether was dropped, so Aurora could not attach to the window this entry opens:\n{launch:?}"
    );

    fs::remove_file(&rom).expect("remove the fixture ROM");
    let said = say(&launch);
    assert!(
        !said.contains("unknown flag"),
        "this binary's parser REJECTED a token in the argv its own desktop entry produces, which is the \
         defect this gate exists for:\n{said}"
    );
    assert!(
        !said.contains("--rom is required"),
        "the entry reached this binary without a --rom, which is the icon-click defect:\n{said}"
    );
    assert!(
        said.contains("cannot read ROM"),
        "the run never reached the ROM read, so parsing cannot be said to have succeeded and the two \
         assertions above witness nothing:\n{said}"
    );
}

/// ⚑ **The negative control, and the reason the assertions above are not vacuous.** The `Exec=` shape
/// this entry USED to carry, `<binary> <rom>`, is fed to the same binary through the same helper. It must
/// be refused. If this went green the rig would be one in which every argv looks accepted, and the gate
/// above would prove nothing about the argv it checks.
#[test]
fn the_old_positional_exec_shape_is_still_refused_by_this_parser() {
    let rig = Rig::new("control");
    let bin = env!("CARGO_BIN_EXE_oracle-player");
    let rom = rig.root.join("fixture.bin");

    let said = say(&[bin.to_string(), rom.display().to_string()]);
    assert!(
        said.contains("unknown flag"),
        "a bare positional ROM was NOT refused, so this parser no longer distinguishes the two Exec \
         shapes and the gate beside this test is measuring nothing:\n{said}"
    );

    let said = say(&[bin.to_string()]);
    assert!(
        said.contains("--rom is required"),
        "this binary started with no ROM at all, so the launcher's whole reason for existing has \
         changed and this file needs revisiting:\n{said}"
    );
}

/// A plain icon click passes no file, and the entry must still deliver a ROM.
#[test]
fn a_click_with_no_file_selected_still_carries_a_rom() {
    let rig = Rig::new("bare-click");
    let bin = env!("CARGO_BIN_EXE_oracle-player");
    let exec = rig.installed_player_exec(bin);

    let rom = rig.root.join("default.bin");
    fs::write(&rom, b"not a real ROM").expect("fixture ROM");
    let argv = exec_argv(&exec, None);
    let launch = resolved_argv(argv, &rig.path(), Some(&rom.display().to_string()));

    let want = rom.display().to_string();
    let i = launch
        .iter()
        .position(|a| a == "--rom")
        .unwrap_or_else(|| panic!("no --rom in the resolved launch:\n{launch:?}"));
    assert_eq!(
        launch.get(i + 1).map(String::as_str),
        Some(want.as_str()),
        "the ROM the launcher chose is not the one it was given:\n{launch:?}"
    );

    fs::remove_file(&rom).expect("remove the fixture ROM");
    let said = say(&launch);
    assert!(
        said.contains("cannot read ROM"),
        "a click with no file selected did not reach this binary with a usable command line:\n{said}"
    );
}

/// The launcher's `--bin` is a placeholder until the installer substitutes it. An entry that kept the
/// placeholder must refuse rather than guess: guessing would launch something nobody chose.
#[test]
fn an_unsubstituted_placeholder_refuses_rather_than_guessing() {
    let rig = Rig::new("placeholder");
    let rom = rig.root.join("fixture.bin");
    fs::write(&rom, b"not a real ROM").expect("fixture ROM");

    let out = Command::new(launcher())
        .args([
            "--player",
            "--bin",
            "@BIN@",
            "--print-argv",
            &rom.display().to_string(),
        ])
        .env("PATH", rig.path())
        .output()
        .expect("the launcher is runnable");
    let said = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(
        !out.status.success(),
        "an entry still holding @BIN@ was treated as a launchable command line:\n{said}"
    );
    assert!(
        said.contains("install-desktop.sh"),
        "the refusal does not say how to fix it:\n{said}"
    );
}
