//! The window's own identity on the desktop: the Oracle mark as its icon, and a WM class the desktop can
//! resolve to `assets/oracle.desktop`.
//!
//! What the windowing stack allows here is narrow, and it was measured rather than assumed (see the
//! `window-icon` branch log). minifb 0.28 on Linux:
//!
//! * **X11** — [`minifb::Window::set_icon`] writes an `_NET_WM_ICON` property from an ARGB buffer, and the
//!   raw Xlib handles are exposed, so `WM_CLASS` can be set with one `XSetClassHint` call. minifb itself
//!   sets no class at all.
//! * **Wayland** — `set_icon` is `unimplemented!()` (it panics), and minifb never sends `xdg_toplevel.set_app_id`
//!   nor exposes the toplevel, so neither the icon nor the app id can be set from inside the process. KWin
//!   was measured to fall back to the executable name (`resourceClass=oracle-frontend`) — which is what the
//!   `.desktop` entry's `StartupWMClass` matches, so the icon comes from the installed entry there.
//!
//! minifb tries Wayland first and only falls back to X11 when the Wayland connect fails, so `--x11` (which
//! clears `WAYLAND_DISPLAY` for this process before the window opens) is the way to get the in-process icon
//! on a Wayland desktop — the window then lives under XWayland.
//!
//! The embedded asset is `assets/oracle-icon.argb`, generated by `assets/gen-icon.sh` from the ruled suite
//! mark; see that script for the colour choice.

use minifb::{HasWindowHandle, Icon, Window};
use raw_window_handle::RawWindowHandle;

/// `assets/oracle-icon.argb`: records of `[u32 BE w][u32 BE h][w*h × u32 BE ARGB]`, several sizes back to back.
pub const ICON_ARGB: &[u8] = include_bytes!("../assets/oracle-icon.argb");

/// The class the window is stamped with on X11, and what `assets/oracle.desktop` names in `StartupWMClass`.
/// It is the executable name because that is what KWin derives on Wayland (where nothing can be set), so one
/// `.desktop` entry matches both backends.
pub const WM_CLASS: &str = "oracle-frontend";

/// One decoded icon size.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IconImage {
    pub width: u32,
    pub height: u32,
    /// Row-major `0xAARRGGBB`.
    pub argb: Vec<u32>,
}

/// Decode the concatenated-record blob. Returns `None` on a truncated or malformed blob rather than
/// panicking — the asset is checked in and unit-tested, so `None` here means the build is broken, and the
/// caller degrades to "no icon" rather than refusing to open a window.
pub fn decode(blob: &[u8]) -> Option<Vec<IconImage>> {
    let mut out = Vec::new();
    let mut at = 0usize;
    let word = |i: usize| -> Option<u32> {
        blob.get(i..i + 4)
            .map(|b| u32::from_be_bytes([b[0], b[1], b[2], b[3]]))
    };
    while at < blob.len() {
        let width = word(at)?;
        let height = word(at + 4)?;
        let count = (width as usize).checked_mul(height as usize)?;
        if width == 0 || height == 0 {
            return None;
        }
        let start = at + 8;
        let end = start.checked_add(count.checked_mul(4)?)?;
        if end > blob.len() {
            return None;
        }
        let argb = (start..end).step_by(4).map(|i| word(i).unwrap()).collect();
        out.push(IconImage {
            width,
            height,
            argb,
        });
        at = end;
    }
    if out.is_empty() {
        None
    } else {
        Some(out)
    }
}

/// The `_NET_WM_ICON` property payload: for every size, `width, height, pixels…` as 32-bit CARDINALs, which
/// Xlib takes as `c_long` — hence `u64` on LP64 (that is also the element type minifb's `Icon::Buffer`
/// carries).
pub fn net_wm_icon(images: &[IconImage]) -> Vec<u64> {
    let mut v = Vec::new();
    for im in images {
        v.push(u64::from(im.width));
        v.push(u64::from(im.height));
        v.extend(im.argb.iter().map(|&p| u64::from(p)));
    }
    v
}

/// What [`apply`] managed to do, for the run log.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Applied {
    /// X11: `_NET_WM_ICON` and `WM_CLASS` both set.
    X11,
    /// Wayland: nothing can be set from here (see the module doc); the `.desktop` entry carries the icon.
    Wayland,
    /// Some other backend, or the asset failed to decode.
    Nothing,
}

/// Stamp the window with the Oracle icon and class where the backend allows it.
pub fn apply(window: &mut Window) -> Applied {
    let Some(images) = decode(ICON_ARGB) else {
        return Applied::Nothing;
    };
    let raw = match window.window_handle() {
        Ok(h) => h.as_raw(),
        Err(_) => return Applied::Nothing,
    };
    match raw {
        RawWindowHandle::Xlib(xw) => {
            let buf = net_wm_icon(&images);
            // `Icon::Buffer` holds a raw pointer; minifb copies the data into the property synchronously
            // inside `set_icon` (XChangeProperty with PropModeReplace), so `buf` only has to outlive the call.
            window.set_icon(Icon::Buffer(buf.as_ptr(), buf.len() as u32));
            drop(buf);
            x11_class::set(window, xw.window);
            Applied::X11
        }
        RawWindowHandle::Wayland(_) => Applied::Wayland,
        _ => Applied::Nothing,
    }
}

/// `WM_CLASS` via Xlib, using the Display minifb already opened.
#[cfg(target_os = "linux")]
mod x11_class {
    use super::WM_CLASS;
    use minifb::Window;
    use raw_window_handle::{HasDisplayHandle, RawDisplayHandle};
    use std::ffi::CString;
    use x11_dl::xlib;

    pub fn set(window: &Window, xid: std::os::raw::c_ulong) {
        let Ok(dh) = window.display_handle() else {
            return;
        };
        let RawDisplayHandle::Xlib(xd) = dh.as_raw() else {
            return;
        };
        let Some(display) = xd.display else {
            return;
        };
        let Ok(lib) = xlib::Xlib::open() else {
            return;
        };
        let name = CString::new(WM_CLASS).expect("no NUL in WM_CLASS");
        let mut hint = xlib::XClassHint {
            res_name: name.as_ptr() as *mut _,
            res_class: name.as_ptr() as *mut _,
        };
        // SAFETY: `display` is the live Xlib Display minifb opened for this window and `xid` is that
        // window's id (both straight from raw-window-handle); `hint` points at a NUL-terminated string that
        // outlives the call, and XSetClassHint copies it into the property before returning.
        unsafe {
            (lib.XSetClassHint)(display.as_ptr() as *mut xlib::Display, xid, &mut hint);
            (lib.XFlush)(display.as_ptr() as *mut xlib::Display);
        }
    }
}

#[cfg(not(target_os = "linux"))]
mod x11_class {
    pub fn set(_window: &minifb::Window, _xid: std::os::raw::c_ulong) {}
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The checked-in asset decodes to the sizes `gen-icon.sh` writes (32/64/128, read back from each
    /// record's own header) and every size actually carries the mark — at least one opaque pixel, and the
    /// pixel count matches the header, so a truncated or blank regeneration cannot land silently.
    #[test]
    fn the_embedded_icon_decodes_and_is_not_blank() {
        let images = decode(ICON_ARGB).expect("asset decodes");
        let sizes: Vec<(u32, u32)> = images.iter().map(|i| (i.width, i.height)).collect();
        assert_eq!(sizes, vec![(32, 32), (64, 64), (128, 128)]);
        for im in &images {
            assert_eq!(im.argb.len(), (im.width * im.height) as usize);
            assert!(
                im.argb.iter().any(|&p| p >> 24 != 0),
                "{}x{} is fully transparent",
                im.width,
                im.height
            );
            // The tint is the Oracle accent: some pixel must be blue-heavy, not just the dark disc.
            assert!(
                im.argb
                    .iter()
                    .any(|&p| (p & 0xFF) > 0xC0 && (p >> 24) == 0xFF),
                "{}x{} carries no cyan stroke",
                im.width,
                im.height
            );
        }
        // Every byte of the blob was consumed by a record — no trailing junk.
        let total: usize = images.iter().map(|i| 8 + i.argb.len() * 4).sum();
        assert_eq!(total, ICON_ARGB.len());
    }

    /// `_NET_WM_ICON` layout: `w, h, pixels…` per size, back to back.
    #[test]
    fn net_wm_icon_is_width_height_then_pixels_per_size() {
        let images = vec![
            IconImage {
                width: 1,
                height: 2,
                argb: vec![0xFF00_0000, 0x8012_3456],
            },
            IconImage {
                width: 1,
                height: 1,
                argb: vec![0x0000_0001],
            },
        ];
        assert_eq!(
            net_wm_icon(&images),
            vec![1, 2, 0xFF00_0000, 0x8012_3456, 1, 1, 1]
        );
    }

    /// Malformed blobs are refused, never panicked on.
    #[test]
    fn decode_refuses_truncated_or_empty_blobs() {
        assert_eq!(decode(&[]), None);
        assert_eq!(decode(&[0, 0, 0, 1]), None, "header cut short");
        assert_eq!(decode(&[0, 0, 0, 1, 0, 0, 0, 1]), None, "no pixels");
        assert_eq!(
            decode(&[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
            None,
            "zero width"
        );
        let one = decode(&[0, 0, 0, 1, 0, 0, 0, 1, 0xAA, 0xBB, 0xCC, 0xDD]).unwrap();
        assert_eq!(
            one,
            vec![IconImage {
                width: 1,
                height: 1,
                argb: vec![0xAABB_CCDD]
            }]
        );
    }
}
