//! **Who answered, and which build of it** — contract `protocol.md` §2.1, registered 2026-08-26 by
//! §11.23.
//!
//! Two values with one property in common and it is the whole reason they live here rather than in
//! [`crate::server::ServerConfig`]: **neither is forgeable by configuration**. §2.1 is explicit — *"A
//! server MUST NOT make either settable by config file, config struct, environment variable,
//! command-line flag or bus method."* A contract cannot stop a process putting arbitrary bytes on a
//! socket; what it can do is make forging these a violation rather than a supported configuration. So the
//! check is source-level, and `tests/server_build.rs` performs it: no `EngineConfig` field, no
//! `std::env::var`, no argument parser reaches either value.
//!
//! [`IMPLEMENTATION`] is a literal because the registry it draws from is a table in §2.1 that only an
//! amendment may extend; a value outside it is non-conformant, which is the point of a registry.
//!
//! [`SERVER_BUILD_ID`], [`SERVER_BUILD_SOURCE`], [`SERVER_BUILD_DIRTY`] and
//! [`SERVER_BUILD_DIRTY_SCOPE`] come from `build.rs` by way of
//! `$OUT_DIR/build_info.rs` and the `include!` below. §2.1's ⚑ clause names exactly this arrangement as
//! conformant: *"a file generated by the build and `include!`d … is on the compile-time side of it"*. The
//! line it draws is compile time versus run time, not file versus constant — and moving any of these to
//! something read at start-up is, in the contract's own words, *"a regression against this clause, not a
//! refactor"*. `build.rs`'s module doc carries the derivation and the invalidation argument.

/// Which implementation of the contract answered (§2.1's registry: `oracle-rs` | `oracle-cpp`).
///
/// **Not `serverName`.** §2.1: *"`serverName` remains a **deployment** label a config may set — two
/// processes of the same implementation on one machine want distinguishable names — and MUST NOT be used
/// to discriminate implementations."* This repo's own suite was doing precisely that (pinning
/// `serverName == "oracle-next"`) until §11.23 landed, which is the pin §11.23's closing paragraph names.
pub const IMPLEMENTATION: &str = "oracle-rs";

include!(concat!(env!("OUT_DIR"), "/build_info.rs"));
